insert into my_contacts (first_name,last_name,email,gender,birthday,location)
values
('Anderson', 'Jillian', 'jill_anderson@breakneckpizza.net', 'F', '1996-2-13', 'Palo Alto, CA') ,
('Joffe', 'Kevin', 'joffe@simuduck.com', 'M', '2002-2-8', 'San Jose, CA') ,
('Newsome', 'Amanda', 'aman2luv@breakneckpizza.net', 'F', '1997-5-13', 'San Fran, CA') ,
('Garcia', 'Ed', 'ed99@b0tt0msup.com', 'M', '2000-2-4', 'San Mateo, CA') ,
('Roundtree', 'Jo-Ann', 'jojoround@breakneckpizza.net', 'F', '1996-11-24', 'San Fran, CA') ,
('Briggs', 'Chris', 'cbriggs@boards-r-us.com', 'M', '2003-11-9', 'Austin, TX') ,
('Harte', 'Lloyd', 'hovercraft@breakneckpizza.net', 'M', '1992-10-9', 'San Jose, CA') ,
('Toth', 'Anne', 'Anne_Toth@leapinlimos.com', 'F', '1998-4-19', 'San Fran, CA') ,
('Wiley', 'Andrew', 'andrewwiley@objectville.net', 'M', '1994-5-17', 'NYC, NY') ,
('Palumbo', 'Tom', 'palofmine@mightygumball.net', 'M', '1990-1-11', 'Princeton, NJ') ,
('Ryan', 'Alanna', 'angrypirate@breakneckpizza.net', 'F', '1990-8-19', 'San Fran, CA') ,
('McKinney', 'Clay', 'clay@starbuzzcoffee.com', 'M', '2000-12-9', 'NYC, NY') ,
('Meeker', 'Ann', 'ann_meeker@chocoholic-inc.com', 'F', '1990-5-24', 'San Fran, CA') ,
('Powers', 'Brian', 'bp@honey-doit.com', 'M', '1996-11-7', 'Napa, CA') ,
('Manson', 'Anne', 'am86@objectville.net', 'M', '1992-12-8', 'Seattle, WA') ,
('Mandel', 'Debra', 'debmonster@breakneckpizza.net', 'F', '2001-7-27', 'Natchez, MS') ,
('Tedesco', 'Janis', 'janistedesco@starbuzzcoffee.com', 'F', '1995-4-16', 'Las Vegas, NV') ,
('Talwar', 'Vikram', 'vikt@starbuzzcoffee.com', 'M', '2000-1-2', 'Palo Alto, CA') ,
('Szwed', 'Joe', 'szwed_joe@objectville.net', 'M', '2004-5-14', 'NYC, NY') ,
('Sheridan', 'Diana', 'sheridi@mightygumball.net', 'F', '1997-1-17', 'Phoenix, AZ') ,
('Snow', 'Edward', 'snowman@tikibeanlounge.com', 'M', '1998-3-13', 'Fargo, ND') ,
('Otto', 'Glenn', 'glenn0098@objectville.net', 'M', '1990-3-3', 'Boulder, CO') ,
('Hardy', 'Anne', 'anneh@b0tt0msup.com', 'F', '1995-4-13', 'San Fran, CA') ,
('Deal', 'Mary', 'nobigdeal@starbuzzcoffee.com', 'F', '1999-3-17', 'Boston, MA') ,
('Jagel', 'Ann', 'dreamgirl@breakneckpizza.net', 'F', '1996-10-19', 'San Fran, CA') ,
('Melfi', 'James', 'drmelfi@b0tt0msup.com', 'M', '1990-12-3', 'Dallas, TX') ,
('Oliver', 'Lee', 'lee_oliver@weatherorama.com', 'M', '1990-9-22', 'St. Louis, MO') ,
('Parker', 'Anne', 'annep@starbuzzcoffee.com', 'F', '2003-9-18', 'San Fran, CA') ,
('Ricci', 'Peter', 'ricciman@tikibeanlounge.com', 'M', '1990-7-12', 'Reno, NV') ,
('Reno', 'Grace', 'grace23@objectville.net', 'F', '2003-3-28', 'Palo Alto, CA') ,
('Moss', 'Zelda', 'zelda@weatherorama.com', 'F', '2000-8-20', 'Sunnyvale, CA') ,
('Day', 'Clifford', 'cliffnight@breakneckpizza.net', 'M', '1998-4-12', 'Chester, NJ') ,
('Bolger', 'Joyce', 'joyce@chocoholic-inc.com', 'F', '1991-10-27', 'Austin, TX') ,
('Blunt', 'Anne', 'anneblunt@breakneckpizza.net', 'F', '1999-1-27', 'San Fran, CA') ,
('Bolling', 'Lindy', 'lindy@tikibeanlounge.com', 'F', '1998-2-10', 'San Diego, CA') ,
('Gares', 'Fred', 'fgares@objectville.net', 'M', '1993-8-22', 'San Jose, CA') ,
('Jacobs', 'Anne', 'anne99@objectville.net', 'F', '2001-2-30', 'San Jose, CA') ,
('Ingram', 'Dean', 'deaningram@breakneckpizza.net', 'M', '2002-11-11', 'Miami, FL') ;